### ISSUE TITLE
Cannot generate desirable images

### ISSUE THREAD

**Issue by Kenneth-Wong** [ziqihuangg/ReVersion#5]
After finetuning the "ride_on", it cannot generate the images like "child \<R\> panda". What's the problem?
![image](https://github.com/ziqihuangg/ReVersion/assets/23736866/9096b08a-1aa5-43c6-8c7e-c7916ea668d4)

**Comment by ziqihuangg** [comment]
Thanks for the question. ReVersion indeed has its limitations because its performance is capped by the generative capabilities of the pre-trained Stable Diffusion (SD).

SD suffers from the "concept mixing" problem. That is, when the model generates multiple entities within a single scene, SD sometimes fails to generate one of the entity, or, it mixes the characteristics from different entities. For example, when tasked to generate a "rabbit" and a "cat" in an image, SD generates cats with rabbit ears or rabbits with cat-like fur color and texture, or fails to generate either the cat or the rabbit. Since ReVersion does not fine-tune the SD UNet, the same problem might occur, even with a well-learned \<R\>.

**Using ReVersion**: prompt -- _"child <R> panda"_
SD fails to generate the "child", but can showcase some "ride_on" concept.
![0006](https://github.com/ziqihuangg/ReVersion/assets/66513392/1e9296a3-345e-4f9a-85ca-c20cb84ed605)

**Using SD text-to-image, without ReVersion**: prompt -- _"child rides on panda"_
SD fails to generate the child, and often cannot show case the "ride on" concept.
![0006](https://github.com/ziqihuangg/ReVersion/assets/66513392/2574682a-769c-48d4-8600-54370ccae771)
